[package]
edition = "2021"
name = "setver"
description = "SetVer versioning scheme implementation in Rust"
version = "0.2.0"
license-file = "LICENSE"
repository = "https://github.com/kleinesfilmroellchen/rust-setver"
